baseURL = 'https://ziglang.cc'
languageCode = 'en'
defaultContentLanguage = 'zh-cn'
title = 'Zig 语言中文社区'

[[menu.main]]
  name = "主页"
  weight = 10
  url = "/"
[[menu.main]]
  name = "日报"
  weight = 11
  url = "https://github.com/zigcc/forum/issues"
[[menu.main]]
  name = "月刊"
  weight = 20
  url = "/monthly"
[[menu.main]]
  name = "文章"
  weight = 21
  url = "/post"
[[menu.main]]
  name = "新闻"
  weight = 22
  url = "/news"
[[menu.main]]
  name = "论坛"
  weight = 30
  url = "https://ask.ziglang.cc"
# [[menu.main]]
#   name = "Tags"
#   weight = 3
#   url = "/tags"
# [[menu.main]]
#   name = "关于"
#   weight = 4
#   url = "/about"
# [[menu.main]]
#   name = "RSS"
#   weight = 50
#   url = "/index.xml"

[params]
  description = ""
  dateFormat = "Jan 2, 2006"
  gitRepo = "https://github.com/zigcc/zigcc.github.io"
  [params.giscus]
    repo = "zigcc/zigcc.github.io"
    repoId = "R_kgDOHr7nSg"
    category = "Announcements"
    categoryId = "DIC_kwDOHr7nSs4CQUsK"

[module]
  [[module.imports]]
    path = "github.com/jiacai2050/hugo-xmin"

[frontmatter]
  date = [":filename", ":default", ":fileModTime"]
  lastmod = ['lastmod', ':git', ':fileModTime', ':default']

[permalinks]
  post = "/post/:year/:month/:day/:slug/"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 8
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  # https://gohugo.io/getting-started/configuration-markup/#highlight
  [markup.highlight]
    style = "pygments"
    linenos = true